services:
  - type: worker
    name: lisa-bot
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: LISA_HEADLESS
        value: "1"
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FISH_AUDIO_API
        sync: false
